{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-policies
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/instance: {{ .Release.Name }}-opa
    app.kubernetes.io/part-of: e-gaop
data:
  main.rego: |
    package egaop

    default allow = false

    allow {
        input.agent.type == "llm"
    }

    allow {
        input.agent.type == "tool"
    }

    allow {
        input.agent.type == "orchestrator"
    }

    allow {
        input.agent.type == "evaluator"
    }
{{- end }}
