{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-opa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/instance: {{ .Release.Name }}-opa
    app.kubernetes.io/part-of: e-gaop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opa
      app.kubernetes.io/instance: {{ .Release.Name }}-opa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opa
        app.kubernetes.io/instance: {{ .Release.Name }}-opa
        app.kubernetes.io/part-of: e-gaop
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: opa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:{{ .Values.port }}"
            - "--log-level=info"
            - "/policies/"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          startupProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: policies
              mountPath: /policies
              readOnly: true
      volumes:
        - name: policies
          configMap:
            name: {{ .Release.Name }}-opa-policies
{{- end }}
