{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-secret-store
  namespace: {{ .Release.Namespace }}
data:
  SECRET_STORE_PORT: "{{ .Values.grpcPort }}"
  SECRET_STORE_HEALTH_PORT: "{{ .Values.healthPort }}"
{{- end }}
