{{- if .Values.secret-store.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-secret-store
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: secret-store
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: e-gaop
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-store
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: health
      path: /metrics
      interval: 15s
{{- end }}
