apiVersion: 1
datasources:
  - name: TemporalMetrics
    uid: TemporalMetrics
    type: prometheus
    access: proxy
    url: http://egaop-prometheus-server
    isDefault: true
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://egaop-e-gaop-loki:3100
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://egaop-e-gaop-tempo:3200
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags:
          - key: service.name
            value: service_name
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: TemporalMetrics
      serviceMap:
        datasourceUid: TemporalMetrics
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
