enabled: true

image:
  repository: openpolicyagent/opa
  tag: "0.68.0"
  pullPolicy: IfNotPresent

port: 8181

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

probes:
  startup:
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 12
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 6
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
serviceMonitor:
  enabled: false
