#!/usr/bin/env bash
# E-GAOP Quick Setup — Zero to Running in 5 Minutes
# Usage: ./scripts/setup.sh [--skip-docker] [--skip-openai]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; }
info() { echo -e "${BLUE}[i]${NC} $1"; }

SKIP_DOCKER=false
SKIP_OPENAI=false

for arg in "$@"; do
  case $arg in
    --skip-docker) SKIP_DOCKER=true ;;
    --skip-openai) SKIP_OPENAI=true ;;
    --help|-h)
      echo "Usage: ./scripts/setup.sh [--skip-docker] [--skip-openai]"
      echo ""
      echo "Options:"
      echo "  --skip-docker   Skip Docker build and start"
      echo "  --skip-openai   Skip OpenAI API key prompt"
      exit 0
      ;;
  esac
done

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║        E-GAOP Platform — Quick Setup            ║"
echo "║        Zero to Running in 5 Minutes             ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

# Step 1: Check prerequisites
info "Checking prerequisites..."

check_command() {
  if command -v "$1" &> /dev/null; then
    log "$1 found: $(command -v "$1")"
    return 0
  else
    err "$1 not found. Please install $1."
    return 1
  fi
}

MISSING=false
check_command git || MISSING=true
check_command node || MISSING=true
check_command docker || MISSING=true

if ! command -v docker compose &> /dev/null; then
  err "docker compose (v2) not found. Please install Docker Compose v2."
  MISSING=true
fi

if [ "$MISSING" = true ]; then
  echo ""
  err "Missing prerequisites. Install them and re-run this script."
  exit 1
fi

log "All prerequisites satisfied"
echo ""

# Step 2: Generate .env if not exists
if [ -f "$ENV_FILE" ]; then
  warn ".env file already exists. Skipping generation."
  warn "Delete it and re-run to regenerate: rm .env && ./scripts/setup.sh"
else
  info "Generating .env file with secure defaults..."
  
  JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  POSTGRES_PASSWORD=$(openssl rand -base64 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
  GRAFANA_PASSWORD=$(openssl rand -base64 24 2>/dev/null || node -e "console.log(require('crypto').randomBytes(24).toString('base64'))")
  ENCRYPTION_KEY=$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  SERVICE_TOKEN=$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  
  cat > "$ENV_FILE" << EOF
# E-GAOP Environment Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Core ──────────────────────────────────────────
NODE_ENV=development
LOG_LEVEL=info

# ── Authentication ────────────────────────────────
JWT_SECRET=${JWT_SECRET}

# ── Database ──────────────────────────────────────
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=egaop
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/egaop

# ── Redis ─────────────────────────────────────────
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=changeme

# ── Encryption ────────────────────────────────────
EGAOP_MASTER_ENCRYPTION_KEY=${ENCRYPTION_KEY}
INTERNAL_SERVICE_TOKEN=${SERVICE_TOKEN}

# ── LLM Provider (set your API key) ──────────────
OPENAI_API_KEY=sk-your-key-here

# ── Monitoring ────────────────────────────────────
GRAFANA_USER=admin
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}

# ── Optional: Uncomment to enable ─────────────────
# ANTHROPIC_API_KEY=
# OLLAMA_BASE_URL=http://host.docker.internal:11434
# TLS_ENABLED=false
# SANDBOX_ISOLATION_LEVEL=Standard
EOF

  log ".env file created with secure secrets"
fi

echo ""

# Step 3: OpenAI API key
if [ "$SKIP_OPENAI" = false ]; then
  if grep -q "sk-your-key-here" "$ENV_FILE" 2>/dev/null; then
    echo ""
    warn "OpenAI API key not configured!"
    echo "  1. Get a key from https://platform.openai.com/api-keys"
    echo "  2. Edit .env and set OPENAI_API_KEY=sk-..."
    echo ""
    read -p "Press Enter when you've set your API key (or Ctrl+C to exit)..."
  else
    log "OpenAI API key already configured"
  fi
fi

echo ""

# Step 4: Install dependencies
info "Installing npm dependencies..."
cd "$PROJECT_DIR"
npm install --silent 2>/dev/null
log "Dependencies installed"

echo ""

# Step 5: Build shared package
info "Building shared package..."
cd packages/shared && npm run build --silent 2>/dev/null
cd "$PROJECT_DIR"
log "Shared package built"

echo ""

# Step 6: Docker
if [ "$SKIP_DOCKER" = false ]; then
  info "Building and starting Docker services (this may take a few minutes)..."
  docker compose up -d --build 2>/dev/null
  
  info "Waiting for services to be healthy..."
  sleep 10
  
  # Health check loop
  for i in {1..30}; do
    if curl -sf http://localhost:15051/healthz > /dev/null 2>&1; then
      log "API server is healthy!"
      break
    fi
    if [ "$i" -eq 30 ]; then
      warn "API server not yet healthy. Check: docker compose logs api-server"
    fi
    sleep 2
  done
fi

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║           Setup Complete!                        ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "  Services:"
echo "    API:      http://localhost:3001"
echo "    Health:   http://localhost:15051/healthz"
echo "    Grafana:  http://localhost:3003 (admin/\${GRAFANA_PASSWORD})"
echo "    Swagger:  http://localhost:3001/api/docs"
echo ""
echo "  Quick test:"
echo "    curl http://localhost:15051/healthz"
echo ""
echo "  Create your first agent:"
echo "    curl -X POST http://localhost:3001/api/auth/register \\"
echo "      -H 'Content-Type: application/json' \\"
echo "      -d '{\"name\":\"You\",\"email\":\"you@example.com\",\"password\":\"YourPassword123!\"}'"
echo ""
echo "  Next steps:"
echo "    make status        # Check all services"
echo "    make test          # Run tests"
echo "    make help          # See all commands"
echo ""
