{{- if .Values.sandbox-runtime.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-sandbox-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sandbox-runtime
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: e-gaop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sandbox-runtime
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
