{{- if .Values.api-server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-server
  namespace: {{ .Release.Namespace }}
data:
  API_SERVER_GRPC_PORT: "{{ .Values.api-server.grpcPort }}"
  API_SERVER_HEALTH_PORT: "{{ .Values.api-server.healthPort }}"
  API_SERVER_REST_PORT: "{{ .Values.api-server.restPort }}"
{{- end }}
