enabled: true
image: egaop/sandbox-runtime
tag: latest
replicas: 2
grpcPort: 50054
healthPort: 15054
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
serviceMonitor:
  enabled: false
