{{- if .Values.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-observability-plane
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: observability-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: e-gaop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: observability-plane
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
